name: Release Build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release name (e.g., 1.0.0)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build GovSecureID app bundle
      run: ./gradlew bundleRelease
      
    - name: Sign GovSecureID app Bundle
      id: sign_aab
      uses: ilharp/sign-android-release@v1
      with:
        releaseDir: app/build/outputs/bundle/release/
        signingKey: ${{ secrets.KEYSTORE_BASE64 }}
        keyAlias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        buildToolsVersion: 35.0.0

    - name: Archive signed release bundle
      uses: actions/upload-artifact@v4
      with:
        name: mobile-${{ github.sha }}-release.aab
        path: app/build/outputs/bundle/release/app-release-signed.aab
        retention-days: 2
